// Example and test on how to use the Artcode API, subject to change
#include "components/comp.hpp"
#include <artcode.hpp>

int main() {
    // quad i.e a square
    Art::Quad qd;
    qd.w        = 100;
    qd.l        = 100;
    qd.position = {300, 300};
    qd.color    = "#322322";

    // skewed quad example i.e rectangle, skewPos is a std::array
    // skew follows the "photoshop" model or close as behind the scenes there is a quad
    // mesh for every shape that is created if skew == true, yes, every shapes including
    // the shapes generated by the pen tool
    // this means that there are 8 vertices that can be manipulated from index 0 to 7
    // where the even members i.e the "corners" of the mesh can be move from its x and y
    // axis, the od numbers i.e the bridge between the even numbered instances can only
    // move in there respective axis i.e indices 1 and 5 can only move in x axis while
    // indices 3 and 7 is in y axis
    Art::Quad rc; 
    rc.w        = 300;
    rc.l        = 100;
    rc.fill     = true;
    rc.position = {400, 300};
    rc.skew     = true;
    rc.skewPos  = {{{Vec2{100, 200}, 2}, {Vec2{-200, 400}, 4}, {Vec2{200, 0}, 1}}};
    rc.color    = "#696969";

    // circle with opacity, it ranges from 0.0 to 1.0
    // fill is false by default, no need to add or configure
    Art::Circle cr;
    cr.radius   = 100;
    cr.position = {500, 500};
    cr.stroke   = 5.0f;
    cr.opacity  = 0.5f;
    cr.color    = "#184184";

    // rotate triangle, rotate == degrees
    // this draws an equilateral triangle, to change the type of triangle the type member
    // needs to be updated i.e members = TriangleTypes::Right
    Art::Triangle tr;
    tr.base     = 100;
    tr.height   = 300;
    tr.position = {600, 300};
    tr.fill     = true;
    tr.rotate   = 30;
    tr.color    = "#454647";

    // pen tool example where handle is enabled and have a vec2 position
    // because this is fill = true the last vertex of the pen automatically closes and
    // connects to the first vertex making it a shape with a filled color
    Art::Pen pn;
    pn.positions = {
        {Vec2{100, 100}, {true, Vec2{100, 500}}}, {Vec2{400, 500}}, {Vec2{100, 500}}};
    pn.fill  = true;
    pn.color = "#7FD644";

    // the instances declared in comp will now be created after the pen instance
    // this api follows order of declaration as the identifier of whose shape appears on
    // front first where the first instance declared will always be on front of the
    // artboard declaring the class Component before the Quad qd instance makes the right
    // triangles be the first to render specifucally member rt1
    Component comp;
    // run the right triangles for the function Draw() to draw them
    comp.rightTriangles();

    // draw function is called alaways at the end of all shape instances
    // the draw function is responsible for taking displaying all instances to artboard
    Art::Draw();

    return 0;
};
